version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod --bind_ip_all
    volumes:
      - ./data:/data/db
    ports:
      - '127.0.0.1:27017:27017'